const Actions = {
    ADD_TODO: "ADD_TODO",
    REMOVE_TODO: "REMOVE_TODO",
    TOGGLE_TODO: "TOGGLE_TODO",
    SET_VISIBILITY_FILTER: "SET_VISIBILITY_FILTER",
    ADD_NOTE: "ADD_NOTE",
    REMOVE_NOTE: "REMOVE_NOTE"
};

export default Actions;